### ISSUE TITLE
onLogLine doesn't seem to be working

### ISSUE THREAD

**Issue by Ihellmasker** [hibiyasleep/OverlayPlugin#10]
Hey there. I'm trying to make use of the onLogLine function but it doesn't seem to be doing anything, although I am probably just using it wrong. I'm currently just trying to post any messages into the console just for testing purposes and nothing seems to be happening.

The code I'm using is:
```
document.addEventListener("onLogLine", function (e) {
    console.log(e);
});
```

**Comment by hibiyasleep** [comment]
Maybe FFXIV_ACT_Plugin or FFXIV itself changed something... Before of all, please check your ACT log contains `/e` messages. (`onLogLine` only sends `/echo` messages)

**Comment by Ihellmasker** [comment]
It seems to be working now. I must have been doing something wrong. Unless it got fixed in todays FFXIV plugin update.

Thanks anyway :D
