### ISSUE TITLE
.net Framework CAS Policy for 0.3.3.14

### ISSUE THREAD

**Issue by Elinty** [hibiyasleep/OverlayPlugin#16]
So apperently the overlayplugin.dll requires to have Cas-policy to be enabled
did some looking around and found some guides on how to activate it but no luck so far

im on windows 10 with .net v 4.7

**Comment by bevelle** [comment]
Try "DLL Properties -> General Tab -> Security -> Unblock" for all OverlayPlugin DLLs.  
Or, Unblock Zip File prior to unzip.

**Comment by Elinty** [comment]
Yep i Just figured it out. It was the zip file that was blocked and by extracting it, all files where blocked aswell. Thx for the response  tho grtz elinty
