### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by bsides** [hibiyasleep/OverlayPlugin#36]
As the title says, just to know how things are going. 

Thanks in advance!

**Comment by hibiyasleep** [comment]
Actually yes, because, OverlayPlugin was designed to be works with "CEF Single-Process Mode", but this mode was deprecated long ago. remodeling this code was (seems) very hard, so I made only feature patches excepts CEF upgrade.

**Comment by hibiyasleep** [comment]
And - there's also replacement project, [Aliapoh.Overlay](https://github.com/lalafellsleep/Aliapoh.Overlay), seems nearly completed.

**Comment by bsides** [comment]
Thanks! Also for pointing out the replacement @hibiyasleep
