### ISSUE TITLE
Plugin does not recognise Trusts.

### ISSUE THREAD

**Issue by Dajova** [hibiyasleep/OverlayPlugin#38]
As seen in the screenshot below, the plugin only seems to parse one of the Trust NPCs at any given time and even then, its listed as a chocobo.

![image](https://i.imgur.com/WVc5TF8.png)

I've tried other layouts that has been updated with Shadowbringer and its either OverlayPlugin or my layout (kagerou skin) that needs to be updated to parse them. Not sure who, but posting on both just in case.

**Comment by hibiyasleep** [comment]
OverlayPlugin is just delivering data from ACT to Overlay, without any modifications. so this should be issued on `kagerou` and/or other overlays. thanks!
