### ISSUE TITLE
Issue Loading Plugin into ACT // Error

### ISSUE THREAD

**Issue by WesternFont** [hibiyasleep/OverlayPlugin#40]
After running the build.bat with ACT in the ACT folder. the .dll file added to the x64 and x86 build folders do not initialize in ACT.

C:\Games\Advanced Combat Tracker\ACT Client Folder\OverlayPlugin-0.3.4.0\BuildX64\OverlayPlugin.Common.dll

![Screenshot_5](https://user-images.githubusercontent.com/53983962/62827807-a2647000-bba5-11e9-89be-cebde0020acf.jpg)

**Comment by hibiyasleep** [comment]
You should load `OverlayPlugin.dll`, not `OverlayPlugin.Common.dll`.

I'll close this issue - but feel free to ask other problems here.
