### ISSUE TITLE
Hotkey for toggle clickthrough

### ISSUE THREAD

**Issue by Hoshiyuu** [hibiyasleep/OverlayPlugin#5]
Can there be a global hotkey to toggle "Enable Clickthrough" for overlays?

(Similarly, if this is implemented, can this function be exposed to the Kagerou Overlay for usage like automatically disabling click-through when there is an active encounter?)

Thank you.

**Comment by hibiyasleep** [comment]
I'm doing minimal maintenances and tweaks inside what can I do, but that's too complex to done by me. May somebody can implement this...

**Comment by bevelle** [comment]
I added "Hotkey Type" toggle to miniparse and spelltimer config window.  
You can try unzip attached zip file and replace DLLs.
[add-hotkey-toggle-36c2e76.zip](https://github.com/hibiyasleep/OverlayPlugin/files/1191078/add-hotkey-toggle-36c2e76.zip)

**Comment by hibiyasleep** [comment]
this will included in next update, thanks for contribution!
