### ISSUE TITLE
오버레이 스킨에서 기공사의 max damage 표시 관련

### ISSUE THREAD

**Issue by tgng5463** [hibiyasleep/OverlayPlugin#6]
안녕하세요 미터기 잘 사용하고 있습니다.
기공사로 플레이 중인데요 미터기에 max damage 표시되도록 해놓으면
"충전 포격:844"
이런식으로 포탑의 기술명과 데미지가 표기되고 있어서 문의 드립니다.

**Comment by hibiyasleep** [comment]
OverlayPlugin의 문제가 아니라, 해당 스킨이 포탑/소환수 합산을 제대로 지원하지 않을 때 생기는 문제입니다.
