### ISSUE TITLE
Window titles

### ISSUE THREAD

**Issue by Ihellmasker** [hibiyasleep/OverlayPlugin#7]
Is it possible to make it when a popup window is created (Using something like window.open in Javascript) that those windows will use their title from the title html tag rather than having a blank title?

**Comment by laiglinne-ff** [comment]
https://github.com/hibiyasleep/OverlayPlugin/blob/701f95623ec184049288db68dfbec47c6e660130/HtmlRenderer/Renderer.cs#L76
