### ISSUE TITLE
DirectHit/CritDirectHit support?

### ISSUE THREAD

**Issue by Mitsuma** [hibiyasleep/OverlayPlugin#9]
I'm currently trying to add the new DirectHit and possibly the DirectHitCrit % to some skins.
Looking at the debug output it does not include any of those, trying various variables doesn't work either.

They were added with the latest official release of [1.5.1.0](https://github.com/ravahn/FFXIV_ACT_Plugin/releases).

Not sure if I'm in the right place for this, the original OverlayPlugin github seems to be dead.

**Comment by hibiyasleep** [comment]
At [here](https://github.com/hibiyasleep/OverlayPlugin/blob/master/OverlayPlugin.Core/Overlays/MiniParseOverlay.cs#L257) it reads [EncounterData.ExportVariables](http://advancedcombattracker.com/apidoc/) directly, so I think 'direct hit' wasn't correctly register to ACT-side.

I'll look into this in this weekend, if direct hit can be occured with character in ARR free trial.

**Comment by Mitsuma** [comment]
Can't help with the program side. Just saw that directhit does not get outputted in the debug log.
I can tell you that direct hit can occur in the trial though, that change goes back to lvl1.

**Comment by hibiyasleep** [comment]
thanks!

**Comment by trfunk** [comment]
> An Export variable {DirectHitPct} was added to allow for direct hit to be displayed in overlays.
Another Export variable, {CritDirectHitPct} was added as well. This is the percent of hits that are both direct hit and critical.

According to https://github.com/ravahn/FFXIV_ACT_Plugin/releases/tag/v1.5.1.3 (which was released 20mins ago)

**Comment by Mitsuma** [comment]
Can be closed, yes.
![ffxiv_dx11_2017-06-22_19-46-23](https://user-images.githubusercontent.com/8568089/27448076-ade60fa2-5783-11e7-9a9e-69ab318038c8.jpg)
The new variables work fine with OverlayPlugin.
